// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type CompactionCausality struct {
	ID           int64          `json:"id"`
	SummaryID    sql.NullString `json:"summary_id"`
	SessionID    string         `json:"session_id"`
	Turn         int64          `json:"turn"`
	ToolCallID   sql.NullString `json:"tool_call_id"`
	Tool         string         `json:"tool"`
	ArgsHash     sql.NullString `json:"args_hash"`
	IsError      int64          `json:"is_error"`
	FilesChanged string         `json:"files_changed"`
	CreatedAt    int64          `json:"created_at"`
}

type CompactionEmbedding struct {
	MessageID string         `json:"message_id"`
	SummaryID sql.NullString `json:"summary_id"`
	SessionID string         `json:"session_id"`
	Embedding []byte         `json:"embedding"`
	CreatedAt int64          `json:"created_at"`
}

type CompactionFileRef struct {
	ID          string         `json:"id"`
	SessionID   string         `json:"session_id"`
	Path        string         `json:"path"`
	Mime        sql.NullString `json:"mime"`
	TokenCount  sql.NullInt64  `json:"token_count"`
	Exploration sql.NullString `json:"exploration"`
	FirstSeenAt int64          `json:"first_seen_at"`
}

type CompactionSummary struct {
	ID                     string         `json:"id"`
	SessionID              string         `json:"session_id"`
	ParentIds              string         `json:"parent_ids"`
	CoveredStart           sql.NullInt64  `json:"covered_start"`
	CoveredEnd             sql.NullInt64  `json:"covered_end"`
	FirstRetainedMessageID sql.NullString `json:"first_retained_message_id"`
	Kind                   string         `json:"kind"`
	Level                  int64          `json:"level"`
	SummaryText            string         `json:"summary_text"`
	Layout                 string         `json:"layout"`
	Checkpoint             sql.NullString `json:"checkpoint"`
	TokenCount             int64          `json:"token_count"`
	ModelProvider          sql.NullString `json:"model_provider"`
	ModelID                sql.NullString `json:"model_id"`
	Reasoning              sql.NullString `json:"reasoning"`
	CoveredMessageIds      string         `json:"covered_message_ids"`
	CreatedAt              int64          `json:"created_at"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
}

type MessagesFt struct {
	Parts string `json:"parts"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
	ReserveTokens    int64          `json:"reserve_tokens"`
	KeepRecentTokens int64          `json:"keep_recent_tokens"`
	ActiveSummaryID  sql.NullString `json:"active_summary_id"`
}
