// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateCompactionCausality(ctx context.Context, arg CreateCompactionCausalityParams) error
	CreateCompactionEmbedding(ctx context.Context, arg CreateCompactionEmbeddingParams) error
	CreateCompactionFileRef(ctx context.Context, arg CreateCompactionFileRefParams) (CompactionFileRef, error)
	CreateCompactionSummary(ctx context.Context, arg CreateCompactionSummaryParams) (CompactionSummary, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteCompactionSummary(ctx context.Context, id string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetActiveCompactionSummary(ctx context.Context, sessionID string) (CompactionSummary, error)
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetCompactionFileRef(ctx context.Context, id string) (CompactionFileRef, error)
	GetCompactionFileRefByPath(ctx context.Context, arg GetCompactionFileRefByPathParams) (CompactionFileRef, error)
	GetCompactionSummary(ctx context.Context, id string) (CompactionSummary, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (Message, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetMessageByID(ctx context.Context, id string) (Message, error)
	GetMessagesByCreatedRange(ctx context.Context, arg GetMessagesByCreatedRangeParams) ([]Message, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListChildCompactionSummaries(ctx context.Context, arg ListChildCompactionSummariesParams) ([]CompactionSummary, error)
	ListCompactionCausalityBySession(ctx context.Context, sessionID string) ([]CompactionCausality, error)
	ListCompactionEmbeddingsBySession(ctx context.Context, sessionID string) ([]CompactionEmbedding, error)
	ListCompactionSummariesBySession(ctx context.Context, sessionID string) ([]CompactionSummary, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionCompaction(ctx context.Context, arg UpdateSessionCompactionParams) error
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
}

var _ Querier = (*Queries)(nil)
